import type { ConverterFn, ConvertInput, ConvertResult } from './types';

export const aiConvert: ConverterFn = async (input: ConvertInput, env: Env): Promise<ConvertResult> => {
  const results = await env.AI.toMarkdown([
    {
      name: input.fileName,
      blob: new Blob([input.body], { type: input.contentType }),
    },
  ]);

  const result = results[0];

  if (result.format === 'error') {
    throw new Error(`Conversion failed: ${result.error}`);
  }

  let markdown = result.data ?? '';

  // Strip YAML frontmatter if present (generated by Workers AI toMarkdown)
  markdown = markdown.replace(/^---\n[\s\S]*?\n---\n*/, '');

  return {
    markdown,
    name: result.name,
    mimeType: result.mimeType,
    tokens: result.tokens,
  };
};
